<div id="right-content">

	<h2 class="navhead">HOME</h2>
	<span class="none"> | </span>

	<h2 class="navhead">BLOG</h2>


<h2 class="navhead">LESSONS</h2>


	<a href="1.shtml">01 | introduction</a>
	<span class="none"> | </span>
     

	<a href="2.shtml">02 | tools &amp; standards</a>
	<span class="none"> | </span>

	<a href="3.shtml">03 | HTML 5 &amp; SEO</a>
	<span class="none"> | </span>


	<a href="4.shtml">04 | css concepts</a>
	<span class="none"> | </span>


	<a href="5.shtml">05 | more css</a>
	<span class="none"> | </span>

	<a href="6.shtml">06 | CSS and SSIs</a>
	<span class="none"> | </span>


	<a href="7.shtml">07 | template development</a>
	<span class="none"> | </span>

	<a href="9.shtml">09 | methodology</a>
	<span class="none"> | </span>

	<a href="10.shtml">10 | jQuery / Git</a>
	<span class="none"> | </span>

<h2 class="navhead">RESOURCES</h2>


	<a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#97;&#99;&#97;&#108;&#100;&#101;&#114;&#49;&#64;&#109;&#121;&#46;&#98;&#99;&#105;&#116;&#46;&#99;&#97;">alistair calder</a>
	<span class="none"> | </span>


<h2 class="navhead">FORUM</h2>
	<a href="http://my.bcit.ca/">my.bcit</a>
	<span class="none"> | </span>

	<a href="http://www.bcit.ca/">bcit</a>
	<span class="none"> | </span>

	<a href="http://www.computing.bcit.ca/">bcit: computing</a>
	<span class="none"> | </span>

	<a href="http://www.alistair.com/">alistair.com</a>
	<span class="none"> | </span>



	</div>