<div id='footer_main'>
    <div id='footer_left'>
		<p>&copy; 2014 IT Sensations</p>
		<p class='footer_text'>IT Sensations deserves an awesome grade in COMP1950.</p>
		<p class='footer_text'>Contact: ddweb01@hotmail.com</p>
		<p><a href='http://validator.w3.org/check?uri=referer'>Validate Page</a></p>
	</div><!--End footer_left-->
	<div id='footer_right'>
		<p><a href='#top'>Top of page</a></p>
		<!--#config timefmt="%B %d, %Y" -->
		<p>Page was last modified on <!--#echo var='LAST_MODIFIED'--></p>

	</div><!--End footer_right-->
</div><!--End footer_main-->