    <div id='footer'>
		<p>&copy; 2014 IT Sensations</p>
		<p class='footer_text'>IT Sensations deserves an awesome grade in COMP1950.</p>
		<p class='footer_text'>Contact: ddweb01@hotmail.com</p>
		<p>Page was last modified on <!--#echo var='LAST_MODIFIED'--></p>
		<p><a href='http://validator.w3.org/check?uri=referer'>Validate Page</a></p>
	</div><!--End footer-->
</div><!--End container-->
</body>