<head>
	<title><!--#echo var="page_title" -->COMP1950 Site Docs</title>
	<meta charset="utf-8" />
	<link href="./css/style.css" type="text/css" rel="stylesheet" title="Default" />
	<link href="./css/light_box.css" type="text/css" rel="stylesheet" title="Default" />
	<link href="./css/print.css" type="text/css" rel="alternate stylesheet" title="Print" />

	<script type="text/javascript" src="js/jquery.js"></script>
	<script type="text/javascript" src="js/jquery.lightbox-0.5.js"></script>
	<script type="text/javascript">
	$(function() {
		$('.gallery a').lightBox();
	});
	</script>
</head>
<body>